### ISSUE TITLE
Scheduling priority

### ISSUE THREAD

**Issue by DanGiles** [UCL-ARC/terraform-aws-batch-processing#67]
Batch job errors with the following:_"Either schedulingPriority in job definition or schedulingPriorityOverride is required._" This has been flagged as a [bug](https://github.com/hashicorp/terraform-provider-aws/issues/31226). Need to set a Scheduling priority value in [job definition](https://github.com/UCL-ARC/terraform-aws-batch-processing/blob/26d66a40efe015a897f5c48b2bd7e34f5e086f2e/modules/batch/main.tf#L84-L125)

**Comment by kdurolek** [comment]
Changing queue type to fifo does not solve issue it just deactivates "fair share" feature as a whole, shouldn't be considered as an option when we are interested in sharing fairly our compute recourses between our jobs/workflow.
